version: '3'

services:
  quick-auth:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: quick-auth
    ports:
      - "8000:8000"
    environment:
      - DEPLOY_TYPE=docker
      - FIRST_DEPLOY=true
      - SYSTEM_CONF=prod.yaml
    networks: ["auth"]
  postgres:
    image: postgres
    container_name: postgres
    networks: [ "auth" ]
    environment:
      - POSTGRES_DB=quick_auth
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin

networks:
  auth:
    driver: bridge
