version: '3'

services:
  quick-auth:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: quick-auth
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/local/openresty/configuration:/usr/local/openresty/configuration
    env_file:
      - deploy/quick-auth.env
    networks: ["auth"]
  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    networks: ["auth"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/clickhouse/docker_related_config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml:rw
      - ./deploy/clickhouse/config.xml:/etc/clickhouse-server/config.xml:rw
      - ./deploy/clickhouse/users.xml:/etc/clickhouse-server/users.xml:rw
      - /data/clickhouse/lib:/var/lib/clickhouse:rw
  postgres:
    image: postgres
    container_name: postgres
    networks: [ "auth" ]
    environment:
      POSTGRES_DB: "quick_auth"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
    volumes:
      - /etc/localtime:/etc/localtime:ro

networks:
  auth:
    driver: bridge
