// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameClient = "clients"

// Client mapped from table <clients>
type Client struct {
	ID         string     `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	Name       *string    `gorm:"column:name;type:character varying(127)" json:"name"`
	Describe   *string    `gorm:"column:describe;type:character varying(127)" json:"describe"`
	GrantType  *string    `gorm:"column:grant_type;type:text" json:"grantType"`
	CreateTime *time.Time `gorm:"column:create_time;type:timestamp with time zone;default:now()" json:"createTime"`
	UpdateTime *time.Time `gorm:"column:update_time;type:timestamp with time zone;default:now()" json:"updateTime"`
}

// TableName Client's table name
func (*Client) TableName() string {
	return TableNameClient
}
