// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCode = "codes"

// Code mapped from table <codes>
type Code struct {
	ID         int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	ClientID   *string    `gorm:"column:client_id;type:uuid" json:"clientId"`
	Code       *string    `gorm:"column:code;type:character(31)" json:"code"`
	Scope      *string    `gorm:"column:scope;type:character varying(255)" json:"scope"`
	CreateTime *time.Time `gorm:"column:create_time;type:timestamp with time zone;default:now()" json:"createTime"`
	UpdateTime *time.Time `gorm:"column:update_time;type:timestamp with time zone;default:now()" json:"updateTime"`
}

// TableName Code's table name
func (*Code) TableName() string {
	return TableNameCode
}
