// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProvider = "providers"

// Provider mapped from table <providers>
type Provider struct {
	ID               int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TenantID         int64     `gorm:"column:tenant_id;type:bigint;not null" json:"tenantId"`
	Type             string    `gorm:"column:type;type:character varying(32);not null" json:"type"`
	ClientID         string    `gorm:"column:client_id;type:character varying(255);not null" json:"clientId"`
	ClientSecret     string    `gorm:"column:client_secret;type:character varying(255);not null" json:"clientSecret"`
	AgentID          string    `gorm:"column:agent_id;type:character varying(255);not null" json:"agentId"`
	AuthEndpoint     string    `gorm:"column:auth_endpoint;type:character varying(255);not null" json:"authEndpoint"`
	TokenEndpoint    string    `gorm:"column:token_endpoint;type:character varying(255);not null" json:"tokenEndpoint"`
	UserInfoEndpoint string    `gorm:"column:user_info_endpoint;type:character varying(255);not null" json:"userInfoEndpoint"`
	Scope            string    `gorm:"column:scope;type:character varying(255);not null" json:"scope"`
	ResponseType     string    `gorm:"column:response_type;type:character varying(255);not null" json:"responseType"`
	CreatedAt        time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"createdAt"`
	UpdatedAt        time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updatedAt"`
}

// TableName Provider's table name
func (*Provider) TableName() string {
	return TableNameProvider
}
