// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameResourceNode = "resource_nodes"

// ResourceNode mapped from table <resource_nodes>
type ResourceNode struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TenantID   int64     `gorm:"column:tenant_id;type:bigint;not null" json:"tenantId"`
	ResourceID int64     `gorm:"column:resource_id;type:bigint;not null" json:"resourceId"`
	Name       string    `gorm:"column:name;type:character varying(255);not null" json:"name"`
	Path       string    `gorm:"column:path;type:character varying(255);not null" json:"path"`
	Parent     int64     `gorm:"column:parent;type:bigint;not null" json:"parent"`
	ParentPath int64     `gorm:"column:parent_path;type:bigint;not null" json:"parentPath"`
	Value      string    `gorm:"column:value;type:jsonb;not null;default:'{}'::jsonb" json:"value"`
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"createdAt"`
	UpdatedAt  time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updatedAt"`
}

// TableName ResourceNode's table name
func (*ResourceNode) TableName() string {
	return TableNameResourceNode
}
