// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameResourceRole = "resource_roles"

// ResourceRole mapped from table <resource_roles>
type ResourceRole struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TenantID   int64     `gorm:"column:tenant_id;type:bigint;not null" json:"tenantId"`
	ResourceID int64     `gorm:"column:resource_id;type:bigint;not null" json:"resourceId"`
	Code       string    `gorm:"column:code;type:character varying(255);not null" json:"code"`
	Name       string    `gorm:"column:name;type:character varying(255);not null" json:"name"`
	Describe   string    `gorm:"column:describe;type:character varying(255);not null" json:"describe"`
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"createdAt"`
	UpdatedAt  time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updatedAt"`
	Tenant     Tenant    `json:"tenant"`
}

// TableName ResourceRole's table name
func (*ResourceRole) TableName() string {
	return TableNameResourceRole
}
