// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameResourceJSONUserRole = "resource_json_user_roles"

// ResourceJSONUserRole mapped from table <resource_json_user_roles>
type ResourceJSONUserRole struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TenantID   int64     `gorm:"column:tenant_id;type:bigint;not null" json:"tenantId"`
	JSONPath   string    `gorm:"column:json_path;type:character varying(255);not null" json:"jsonPath"`
	ResourceID int64     `gorm:"column:resource_id;type:bigint;not null" json:"resourceId"`
	UserID     string    `gorm:"column:user_id;type:character(32);not null" json:"userId"`
	RoleID     int64     `gorm:"column:role_id;type:bigint;not null" json:"roleId"`
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"createdAt"`
	UpdatedAt  time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updatedAt"`
}

// TableName ResourceJSONUserRole's table name
func (*ResourceJSONUserRole) TableName() string {
	return TableNameResourceJSONUserRole
}
