// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameResource = "resources"

// Resource mapped from table <resources>
type Resource struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TenantID  int64     `gorm:"column:tenant_id;type:bigint;not null" json:"tenantId"`
	Code      string    `gorm:"column:code;type:character varying(255);not null" json:"code"`
	Type      string    `gorm:"column:type;type:character varying(15);not null" json:"type"`
	Name      string    `gorm:"column:name;type:character varying(255);not null" json:"name"`
	Value     string    `gorm:"column:value;type:jsonb;not null;default:'{}'::jsonb" json:"value"`
	Describe  string    `gorm:"column:describe;type:character varying(255);not null" json:"describe"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updatedAt"`
	Tenant    Tenant    `json:"tenant"`
}

// TableName Resource's table name
func (*Resource) TableName() string {
	return TableNameResource
}
