DROP TABLE IF EXISTS app_secrets;
DROP TABLE IF EXISTS apps;
DROP TABLE IF EXISTS codes;
DROP TABLE IF EXISTS providers;
DROP TABLE IF EXISTS tenants;
DROP TABLE IF EXISTS user_pools;
DROP TABLE IF EXISTS users;
