// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApp = "apps"

// App mapped from table <apps>
type App struct {
	ID        string    `gorm:"column:id;type:character(32);primaryKey" json:"id"`
	Tag       string    `gorm:"column:tag;type:character varying(127);not null" json:"tag"`
	Name      string    `gorm:"column:name;type:character varying(127);not null" json:"name"`
	Describe  string    `gorm:"column:describe;type:character varying(255);not null" json:"describe"`
	Icon      string    `gorm:"column:icon;type:character varying(127);not null" json:"icon"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updatedAt"`
}

// TableName App's table name
func (*App) TableName() string {
	return TableNameApp
}
