// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/lib/pq"

const TableNameArrayTest = "array_test"

// ArrayTest mapped from table <array_test>
type ArrayTest struct {
	ID         int32          `gorm:"column:id;type:integer;not null" json:"id"`
	GrantTypes pq.StringArray `gorm:"column:grant_types;type:character varying(127)[]" json:"grantTypes"`
}

// TableName ArrayTest's table name
func (*ArrayTest) TableName() string {
	return TableNameArrayTest
}
