// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameClientSecret = "client_secrets"

// AppSecret mapped from table <client_secrets>
type AppSecret struct {
	AppID  string `gorm:"column:client_id;type:uuid;primaryKey" json:"clientId"`
	Secret string `gorm:"column:secret;type:character(63);primaryKey" json:"secret"`
	Describe   *string   `gorm:"column:describe;type:character varying(127)" json:"describe"`
	CreateTime time.Time `gorm:"column:create_time;type:timestamp with time zone;not null;default:now()" json:"createTime"`
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp with time zone;not null;default:now()" json:"updateTime"`
}

// TableName AppSecret's table name
func (*AppSecret) TableName() string {
	return TableNameClientSecret
}
