// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/lib/pq"
)

const TableNameClient = "clients"

// App mapped from table <clients>
type App struct {
	ID            string         `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	Name          string         `gorm:"column:name;type:character varying(127);not null" json:"name"`
	Describe      *string        `gorm:"column:describe;type:character varying(127)" json:"describe"`
	GrantTypes    pq.StringArray `gorm:"column:grant_types;type:character varying(127)[]" json:"grantTypes"`
	RedirectUris  pq.StringArray `gorm:"column:redirect_uris;type:character varying(127)[]" json:"redirectUris"`
	TokenExpire   int32          `gorm:"column:token_expire;type:integer;not null" json:"tokenExpire"`
	RefreshExpire int32          `gorm:"column:refresh_expire;type:integer;not null" json:"refreshExpire"`
	CodeExpire    int32          `gorm:"column:code_expire;type:integer;not null" json:"codeExpire"`
	CreateTime    time.Time      `gorm:"column:create_time;type:timestamp with time zone;not null;default:now()" json:"createTime"`
	UpdateTime    time.Time      `gorm:"column:update_time;type:timestamp with time zone;not null;default:now()" json:"updateTime"`
}

// TableName App's table name
func (*App) TableName() string {
	return TableNameClient
}
