// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCode = "codes"

// Code mapped from table <codes>
type Code struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID     int64     `gorm:"column:user_id;type:bigint;not null" json:"userId"`
	AppID      string    `gorm:"column:app_id;type:character(32);not null" json:"appId"`
	Code       string    `gorm:"column:code;type:character(31);not null" json:"code"`
	Scope      string    `gorm:"column:scope;type:character varying(255);not null" json:"scope"`
	State      string    `gorm:"column:state;type:character(31);not null" json:"state"`
	CreateTime time.Time `gorm:"column:create_time;type:timestamp with time zone;not null;default:now()" json:"createTime"`
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp with time zone;not null;default:now()" json:"updateTime"`
}

// TableName Code's table name
func (*Code) TableName() string {
	return TableNameCode
}
