// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProvider = "providers"

// Provider mapped from table <providers>
type Provider struct {
	TenantID     string    `gorm:"column:tenant_id;type:uuid;primaryKey" json:"tenantId"`
	Type         string    `gorm:"column:type;type:character(31);primaryKey" json:"type"`
	ClientID     string    `gorm:"column:client_id;type:uuid;not null" json:"clientId"`
	ClientSecret string    `gorm:"column:client_secret;type:uuid;not null" json:"clientSecret"`
	CreateTime   time.Time `gorm:"column:create_time;type:timestamp with time zone;not null;default:now()" json:"createTime"`
	UpdateTime   time.Time `gorm:"column:update_time;type:timestamp with time zone;not null;default:now()" json:"updateTime"`
}

// TableName Provider's table name
func (*Provider) TableName() string {
	return TableNameProvider
}
