// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTenant = "tenants"

// Tenant mapped from table <tenants>
type Tenant struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ClientID   string    `gorm:"column:client_id;type:uuid;not null" json:"clientId"`
	UserPoolID int64     `gorm:"column:user_pool_id;type:bigint;not null" json:"userPoolId"`
	Type       int32     `gorm:"column:type;type:integer;not null" json:"type"`
	Name       string    `gorm:"column:name;type:character varying(127);not null" json:"name"`
	Host       string    `gorm:"column:host;type:character varying(127);not null" json:"host"`
	Company    string    `gorm:"column:company;type:character varying(127);not null" json:"company"`
	Describe   *string   `gorm:"column:describe;type:character varying(127)" json:"describe"`
	CreateTime time.Time `gorm:"column:create_time;type:timestamp with time zone;not null;default:now()" json:"createTime"`
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp with time zone;not null;default:now()" json:"updateTime"`
}

// TableName Tenant's table name
func (*Tenant) TableName() string {
	return TableNameTenant
}
