// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://github.com/hello-jiangxiaoyu/QuickAuth/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/quick/.well-known/jwks.json": {
            "get": {
                "description": "get jwks",
                "tags": [
                    "oidc"
                ],
                "summary": "get jwks",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/.well-known/openid-configuration": {
            "get": {
                "description": "get open id configuration",
                "tags": [
                    "oidc"
                ],
                "summary": "get OIDC",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/oauth.OpenidConfigurationDto"
                        }
                    }
                }
            }
        },
        "/api/quick/apps": {
            "get": {
                "description": "list apps",
                "tags": [
                    "app"
                ],
                "summary": "apps info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "create app",
                "tags": [
                    "app"
                ],
                "summary": "create app",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "description": "body",
                        "name": "bd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AppReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/apps/{appId}": {
            "get": {
                "description": "list apps",
                "tags": [
                    "app"
                ],
                "summary": "apps info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "app id",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "modify app",
                "tags": [
                    "app"
                ],
                "summary": "modify app",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "app id",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "bd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AppReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "delete app",
                "tags": [
                    "app"
                ],
                "summary": "delete app",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "app id",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/apps/{appId}/secrets": {
            "get": {
                "description": "list app secret",
                "tags": [
                    "app"
                ],
                "summary": "app secret info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "app id",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "create app secret",
                "tags": [
                    "app"
                ],
                "summary": "create app secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "app id",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "bd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AppSecretReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/apps/{appId}/secrets/{secretId}": {
            "put": {
                "description": "create app secret",
                "tags": [
                    "app"
                ],
                "summary": "create app secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "app id",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "secret id",
                        "name": "secretId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "bd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AppSecretReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "delete app secret",
                "tags": [
                    "app"
                ],
                "summary": "delete app secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "app id",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "secret id",
                        "name": "secretId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/apps/{appId}/tenants": {
            "get": {
                "description": "get tenant list",
                "tags": [
                    "tenant"
                ],
                "summary": "get tenant list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "app id",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "create tenant",
                "tags": [
                    "tenant"
                ],
                "summary": "create tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "app id",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "bd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.TenantReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/apps/{appId}/tenants/{tenantId}": {
            "get": {
                "description": "get tenant details",
                "tags": [
                    "tenant"
                ],
                "summary": "get tenant details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "app id",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "tenant id",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "modify tenant",
                "tags": [
                    "tenant"
                ],
                "summary": "modify tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "app id",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "tenant id",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "bd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.TenantReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "delete tenant",
                "tags": [
                    "tenant"
                ],
                "summary": "delete tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "app id",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "tenant id",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/login": {
            "post": {
                "description": "login using username and password",
                "tags": [
                    "login"
                ],
                "summary": "login a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "next",
                        "name": "next",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/login/providers/{provider}": {
            "get": {
                "description": "login third provider callback",
                "tags": [
                    "login"
                ],
                "summary": "provider callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "provider name",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/logout": {
            "get": {
                "description": "logout current user",
                "tags": [
                    "login"
                ],
                "summary": "logout current user",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/me/profile": {
            "get": {
                "description": "get jwks",
                "tags": [
                    "oidc"
                ],
                "summary": "get jwks",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/oauth2/auth": {
            "get": {
                "description": "oauth2 authorize",
                "tags": [
                    "oidc"
                ],
                "summary": "oauth2 authorize",
                "parameters": [
                    {
                        "type": "string",
                        "description": "client_id",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "scope",
                        "name": "scope",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "response_type",
                        "name": "response_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "redirect_uri",
                        "name": "redirect_uri",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "state",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "nonce",
                        "name": "nonce",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "302": {
                        "description": "Found"
                    }
                }
            }
        },
        "/api/quick/oauth2/token": {
            "post": {
                "description": "oauth2 token",
                "tags": [
                    "oidc"
                ],
                "summary": "oauth2 token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "client_id",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "client_secret",
                        "name": "client_secret",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "code",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "grant_type",
                        "name": "grant_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "redirect_uri",
                        "name": "redirect_uri",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "state",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "nonce",
                        "name": "nonce",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/providers": {
            "get": {
                "description": "list provider info",
                "tags": [
                    "provider"
                ],
                "summary": "provider info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "tenant host",
                        "name": "vhost",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "create provider",
                "tags": [
                    "provider"
                ],
                "summary": "create provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "tenant host",
                        "name": "vhost",
                        "in": "header"
                    },
                    {
                        "description": "body",
                        "name": "bd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ProviderReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/providers/{providerId}": {
            "get": {
                "description": "get provider details",
                "tags": [
                    "provider"
                ],
                "summary": "get provider details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "tenant host",
                        "name": "vhost",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "provider id",
                        "name": "providerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "modify provider",
                "tags": [
                    "provider"
                ],
                "summary": "modify provider",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "provider id",
                        "name": "providerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "tenant host",
                        "name": "vhost",
                        "in": "header"
                    },
                    {
                        "description": "body",
                        "name": "bd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ProviderReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "delete provider",
                "tags": [
                    "provider"
                ],
                "summary": "delete provider",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "provider id",
                        "name": "providerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "tenant host",
                        "name": "vhost",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/redirect-uri": {
            "get": {
                "description": "get redirect uri list",
                "tags": [
                    "tenant"
                ],
                "summary": "get redirect uri list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "tenant host",
                        "name": "vhost",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "create app redirect uri",
                "tags": [
                    "tenant"
                ],
                "summary": "create app redirect uri",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "tenant host",
                        "name": "vhost",
                        "in": "header"
                    },
                    {
                        "description": "body",
                        "name": "bd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RedirectUriReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/redirect-uri/{uriId}": {
            "put": {
                "description": "modify app",
                "tags": [
                    "tenant"
                ],
                "summary": "modify app redirect uri",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "tenant host",
                        "name": "vhost",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "uri id",
                        "name": "uriId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "bd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RedirectUriReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/redirect-uri/{uri}": {
            "delete": {
                "description": "delete app",
                "tags": [
                    "tenant"
                ],
                "summary": "delete app",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "tenant host",
                        "name": "vhost",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "uri name",
                        "name": "uri",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/register": {
            "post": {
                "description": "login using username and password",
                "tags": [
                    "login"
                ],
                "summary": "login a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "next",
                        "name": "next",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/resources": {
            "get": {
                "tags": [
                    "resource"
                ],
                "summary": "list resources",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "resource"
                ],
                "summary": "create resource",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/quick/resources/{resourceId}": {
            "get": {
                "tags": [
                    "resource"
                ],
                "summary": "get resource",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "resource"
                ],
                "summary": "update resource",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "tags": [
                    "resource"
                ],
                "summary": "delete resource",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/resources/{resourceId}/json/operations/{operationId}/nodes": {
            "get": {
                "tags": [
                    "resource-user"
                ],
                "summary": "list resource operation nodes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "operation id",
                        "name": "operationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/quick/resources/{resourceId}/json/users/{userId}/roles": {
            "get": {
                "tags": [
                    "resource-user"
                ],
                "summary": "list resource json user roles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "resource-user"
                ],
                "summary": "create resource json user role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/quick/resources/{resourceId}/json/users/{userId}/roles/{roleId}": {
            "put": {
                "tags": [
                    "resource-user"
                ],
                "summary": "update resource json user role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "role id",
                        "name": "roleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "tags": [
                    "resource-user"
                ],
                "summary": "delete resource json user role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "role id",
                        "name": "roleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/resources/{resourceId}/nodes": {
            "get": {
                "tags": [
                    "resource-node"
                ],
                "summary": "list resource nodes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "resource-node"
                ],
                "summary": "create resource node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/quick/resources/{resourceId}/nodes/{nodeId}": {
            "get": {
                "tags": [
                    "resource-node"
                ],
                "summary": "get resource node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "nodeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "resource-node"
                ],
                "summary": "update resource node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "nodeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "tags": [
                    "resource-node"
                ],
                "summary": "delete resource node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "nodeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/resources/{resourceId}/operations": {
            "get": {
                "tags": [
                    "resource-node"
                ],
                "summary": "list resource operations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "resource-node"
                ],
                "summary": "create resource operation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/quick/resources/{resourceId}/operations/{operationId}": {
            "get": {
                "tags": [
                    "resource-node"
                ],
                "summary": "get resource operation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "operation id",
                        "name": "operationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "resource-node"
                ],
                "summary": "update resource operation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "operation id",
                        "name": "operationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "tags": [
                    "resource-node"
                ],
                "summary": "delete resource operation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "operation id",
                        "name": "operationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/resources/{resourceId}/roles": {
            "get": {
                "tags": [
                    "resource-node"
                ],
                "summary": "list resource roles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "resource-node"
                ],
                "summary": "create resource role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/quick/resources/{resourceId}/roles/{roleId}": {
            "get": {
                "tags": [
                    "resource-node"
                ],
                "summary": "get resource role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "role id",
                        "name": "roleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "resource-node"
                ],
                "summary": "update resource role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "role id",
                        "name": "roleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "tags": [
                    "resource-node"
                ],
                "summary": "delete resource role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "role id",
                        "name": "roleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/resources/{resourceId}/roles/{roleId}/operations": {
            "get": {
                "tags": [
                    "resource-role-operation"
                ],
                "summary": "list resource role operations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "role id",
                        "name": "roleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "resource-role-operation"
                ],
                "summary": "create resource role operation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "role id",
                        "name": "roleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/quick/resources/{resourceId}/roles/{roleId}/operations/{operationId}": {
            "delete": {
                "tags": [
                    "resource-role-operation"
                ],
                "summary": "delete resource role operation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "role id",
                        "name": "roleId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "operation id",
                        "name": "operationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/resources/{resourceId}/users/{userId}/roles": {
            "get": {
                "tags": [
                    "resource-user"
                ],
                "summary": "list resource json user roles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "resource-user"
                ],
                "summary": "create resource json user role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/quick/resources/{resourceId}/users/{userId}/roles/{roleId}": {
            "put": {
                "tags": [
                    "resource-user"
                ],
                "summary": "update resource json user role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "role id",
                        "name": "roleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "tags": [
                    "resource-user"
                ],
                "summary": "delete resource json user role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "role id",
                        "name": "roleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/user-pools": {
            "get": {
                "description": "list user pool",
                "tags": [
                    "user"
                ],
                "summary": "user pools info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "create user pool",
                "tags": [
                    "user"
                ],
                "summary": "create user pool",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "description": "body",
                        "name": "bd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserPoolReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/user-pools/{poolId}": {
            "get": {
                "description": "list user pool",
                "tags": [
                    "user"
                ],
                "summary": "user pool info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "user pool id",
                        "name": "poolId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "modify user pool",
                "tags": [
                    "user"
                ],
                "summary": "modify user pool",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "user pool id",
                        "name": "poolId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "bd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserPoolReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "delete user pool",
                "tags": [
                    "user"
                ],
                "summary": "delete user pool",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "user pool id",
                        "name": "poolId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/user-pools/{poolId}/users": {
            "get": {
                "description": "list users",
                "tags": [
                    "user"
                ],
                "summary": "user info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "user pool id",
                        "name": "poolId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "create user",
                "tags": [
                    "user"
                ],
                "summary": "create user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "user pool id",
                        "name": "poolId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "bd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/quick/user-pools/{poolId}/users/{userId}": {
            "get": {
                "description": "list user",
                "tags": [
                    "user"
                ],
                "summary": "user info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "user pool id",
                        "name": "poolId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "modify user",
                "tags": [
                    "user"
                ],
                "summary": "modify user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "user pool id",
                        "name": "poolId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "bd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "delete user",
                "tags": [
                    "user"
                ],
                "summary": "delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "X-User-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "user pool id",
                        "name": "X-Pool-ID",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "user pool id",
                        "name": "poolId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "oauth.OpenidConfigurationDto": {
            "type": "object",
            "properties": {
                "authorization_endpoint": {
                    "type": "string"
                },
                "claims_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id_token_signing_alg_values_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "issuer": {
                    "type": "string"
                },
                "jwks_uri": {
                    "type": "string"
                },
                "request_uri_parameter_supported": {
                    "type": "boolean"
                },
                "response_types_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scopes_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "subject_types_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token_endpoint": {
                    "type": "string"
                },
                "token_endpoint_auth_methods_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "userinfo_endpoint": {
                    "type": "string"
                }
            }
        },
        "request.AppReq": {
            "type": "object",
            "required": [
                "describe",
                "host",
                "icon",
                "name",
                "tag"
            ],
            "properties": {
                "describe": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "poolId": {
                    "type": "integer"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "request.AppSecretReq": {
            "type": "object",
            "properties": {
                "accessExpire": {
                    "type": "integer"
                },
                "describe": {
                    "type": "string"
                },
                "refreshExpire": {
                    "type": "integer"
                },
                "scope": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "request.ProviderReq": {
            "type": "object",
            "properties": {
                "agentId": {
                    "type": "string"
                },
                "clientId": {
                    "type": "string"
                },
                "clientSecret": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "request.RedirectUriReq": {
            "type": "object",
            "properties": {
                "uri": {
                    "type": "string"
                }
            }
        },
        "request.TenantReq": {
            "type": "object",
            "required": [
                "company",
                "host",
                "name",
                "userPoolId"
            ],
            "properties": {
                "accessExpire": {
                    "type": "integer"
                },
                "codeExpire": {
                    "type": "integer"
                },
                "company": {
                    "type": "string"
                },
                "describe": {
                    "type": "string"
                },
                "grantTypes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "host": {
                    "type": "string"
                },
                "idExpire": {
                    "type": "integer"
                },
                "isCode": {
                    "type": "boolean"
                },
                "isCredential": {
                    "type": "boolean"
                },
                "isDeviceFlow": {
                    "type": "boolean"
                },
                "isDisabled": {
                    "type": "boolean"
                },
                "isPassword": {
                    "type": "boolean"
                },
                "isRefresh": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "refreshExpire": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                },
                "userPoolId": {
                    "type": "integer"
                }
            }
        },
        "request.UserPoolReq": {
            "type": "object",
            "properties": {
                "describe": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "request.UserReq": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Login": {
            "type": "apiKey",
            "name": "token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Quick Auth 接口文档",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
