definitions:
  controller.OpenidConfigurationDto:
    properties:
      authorization_endpoint:
        type: string
      claims_supported:
        items:
          type: string
        type: array
      id_token_signing_alg_values_supported:
        items:
          type: string
        type: array
      issuer:
        type: string
      jwks_uri:
        type: string
      request_uri_parameter_supported:
        type: boolean
      response_types_supported:
        items:
          type: string
        type: array
      scopes_supported:
        items:
          type: string
        type: array
      subject_types_supported:
        items:
          type: string
        type: array
      token_endpoint:
        type: string
      token_endpoint_auth_methods_supported:
        items:
          type: string
        type: array
      userinfo_endpoint:
        type: string
    type: object
  model.Client:
    type: object
  model.ClientSecret:
    properties:
      clientId:
        type: string
      createTime:
        type: string
      describe:
        type: string
      id:
        type: integer
      secret:
        type: string
      updateTime:
        type: string
    type: object
  model.Provider:
    properties:
      clientId:
        type: string
      clientSecret:
        type: string
      createTime:
        type: string
      tenantId:
        type: string
      type:
        type: string
      updateTime:
        type: string
    type: object
  model.RedirectURI:
    properties:
      clientId:
        type: string
      createTime:
        type: string
      id:
        type: integer
      updateTime:
        type: string
      uri:
        type: string
    type: object
  model.Tenant:
    properties:
      clientId:
        type: string
      company:
        type: string
      createTime:
        type: string
      describe:
        type: string
      host:
        type: string
      id:
        type: string
      name:
        type: string
      type:
        type: integer
      updateTime:
        type: string
      userPoolId:
        type: string
    type: object
  model.UserPool:
    properties:
      createTime:
        type: string
      describe:
        type: string
      id:
        type: string
      name:
        type: string
      updateTime:
        type: string
    type: object
info:
  contact: {}
  license:
    name: MIT
    url: https://github.com/hello-jiangxiaoyu/QuickAuth/blob/main/LICENSE
  title: swagger 接口文档
  version: "1.0"
paths:
  /api/quick/.well-known/jwks.json:
    get:
      description: get jwks
      responses:
        "200":
          description: OK
      summary: get jwks
      tags:
      - oidc
  /api/quick/.well-known/openid-configuration:
    get:
      description: get open id configuration
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.OpenidConfigurationDto'
      summary: get OIDC
      tags:
      - oidc
  /api/quick/clients:
    get:
      description: list clients
      responses:
        "200":
          description: OK
      summary: clients info
      tags:
      - client
    post:
      description: create client
      parameters:
      - description: body
        in: body
        name: bd
        required: true
        schema:
          $ref: '#/definitions/model.Client'
      responses:
        "200":
          description: OK
      summary: create client
      tags:
      - client
  /api/quick/clients/{clientId}:
    delete:
      description: delete client
      parameters:
      - description: client id
        in: path
        name: clientId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: delete client
      tags:
      - client
    get:
      description: list clients
      parameters:
      - description: client id
        in: path
        name: clientId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: clients info
      tags:
      - client
    put:
      description: modify client
      parameters:
      - description: client id
        in: path
        name: clientId
        required: true
        type: string
      - description: body
        in: body
        name: bd
        required: true
        schema:
          $ref: '#/definitions/model.Client'
      responses:
        "200":
          description: OK
      summary: modify client
      tags:
      - client
  /api/quick/clients/{clientId}/redirect-uri:
    get:
      description: get redirect uri list
      parameters:
      - description: client id
        in: path
        name: clientId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: get redirect uri list
      tags:
      - client
    post:
      description: create client
      parameters:
      - description: client id
        in: path
        name: clientId
        required: true
        type: string
      - description: body
        in: body
        name: bd
        required: true
        schema:
          $ref: '#/definitions/model.RedirectURI'
      responses:
        "200":
          description: OK
      summary: create client
      tags:
      - client
  /api/quick/clients/{clientId}/redirect-uri/{uriId}:
    delete:
      description: delete client
      parameters:
      - description: client id
        in: path
        name: clientId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: delete client
      tags:
      - client
    put:
      description: modify client
      parameters:
      - description: client id
        in: path
        name: clientId
        required: true
        type: string
      - description: body
        in: body
        name: bd
        required: true
        schema:
          $ref: '#/definitions/model.RedirectURI'
      responses:
        "200":
          description: OK
      summary: modify client
      tags:
      - client
  /api/quick/clients/{clientId}/secrets:
    get:
      description: list client secret
      parameters:
      - description: client id
        in: path
        name: clientId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: client secret info
      tags:
      - client
    post:
      description: create client secret
      parameters:
      - description: client id
        in: path
        name: clientId
        required: true
        type: string
      - description: body
        in: body
        name: bd
        required: true
        schema:
          $ref: '#/definitions/model.ClientSecret'
      responses:
        "200":
          description: OK
      summary: create client secret
      tags:
      - client
  /api/quick/clients/{clientId}/secrets/{secretId}:
    delete:
      description: delete client secret
      parameters:
      - description: client id
        in: path
        name: clientId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: delete client secret
      tags:
      - client
  /api/quick/clients/{clientId}/tenants:
    get:
      description: list provider info
      parameters:
      - description: client id
        in: path
        name: clientId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: provider info
      tags:
      - tenant
    post:
      description: get provider details
      parameters:
      - description: client id
        in: path
        name: clientId
        required: true
        type: string
      - description: body
        in: body
        name: bd
        required: true
        schema:
          $ref: '#/definitions/model.Tenant'
      responses:
        "200":
          description: OK
      summary: get provider details
      tags:
      - tenant
  /api/quick/clients/{clientId}/tenants/{tenantId}:
    delete:
      description: get provider details
      parameters:
      - description: client id
        in: path
        name: clientId
        required: true
        type: string
      - description: tenant id
        in: path
        name: tenantId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: get provider details
      tags:
      - tenant
    get:
      description: get provider details
      parameters:
      - description: client id
        in: path
        name: clientId
        required: true
        type: string
      - description: tenant id
        in: path
        name: tenantId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: get provider details
      tags:
      - tenant
    put:
      description: get provider details
      parameters:
      - description: client id
        in: path
        name: clientId
        required: true
        type: string
      - description: tenant id
        in: path
        name: tenantId
        required: true
        type: string
      - description: body
        in: body
        name: bd
        required: true
        schema:
          $ref: '#/definitions/model.Tenant'
      responses:
        "200":
          description: OK
      summary: get provider details
      tags:
      - tenant
  /api/quick/login:
    post:
      description: login using username and password
      parameters:
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      - description: next
        in: query
        name: next
        type: string
      responses:
        "200":
          description: OK
      summary: login a user
      tags:
      - login
  /api/quick/login/providers/{provider}:
    get:
      description: login third provider callback
      parameters:
      - description: provider name
        in: path
        name: provider
        required: true
        type: string
      - description: code
        in: query
        name: code
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: provider callback
      tags:
      - login
  /api/quick/logout:
    get:
      description: logout current user
      responses:
        "200":
          description: OK
      summary: logout current user
      tags:
      - login
  /api/quick/oauth2/auth:
    get:
      description: oauth2 authorize
      parameters:
      - description: client_id
        in: query
        name: client_id
        required: true
        type: string
      - description: scope
        in: query
        name: scope
        required: true
        type: string
      - description: response_type
        in: query
        name: response_type
        required: true
        type: string
      - description: redirect_uri
        in: query
        name: redirect_uri
        required: true
        type: string
      - description: state
        in: query
        name: state
        type: string
      - description: nonce
        in: query
        name: nonce
        type: string
      responses:
        "200":
          description: OK
        "302":
          description: Found
      summary: oauth2 authorize
      tags:
      - oauth2
  /api/quick/providers:
    get:
      description: list provider info
      responses:
        "200":
          description: OK
      summary: provider info
      tags:
      - provider
  /api/quick/providers/{providerId}:
    delete:
      description: get provider details
      parameters:
      - description: client id
        in: path
        name: providerId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: get provider details
      tags:
      - provider
    get:
      description: get provider details
      parameters:
      - description: client id
        in: path
        name: providerId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: get provider details
      tags:
      - provider
    post:
      description: get provider details
      parameters:
      - description: client id
        in: path
        name: providerId
        required: true
        type: string
      - description: body
        in: body
        name: bd
        required: true
        schema:
          $ref: '#/definitions/model.Provider'
      responses:
        "200":
          description: OK
      summary: get provider details
      tags:
      - provider
    put:
      description: get provider details
      parameters:
      - description: client id
        in: path
        name: providerId
        required: true
        type: string
      - description: body
        in: body
        name: bd
        required: true
        schema:
          $ref: '#/definitions/model.Provider'
      responses:
        "200":
          description: OK
      summary: get provider details
      tags:
      - provider
  /api/quick/user-pool:
    get:
      description: list user pool
      responses:
        "200":
          description: OK
      summary: user pools info
      tags:
      - user
    post:
      description: create user pool
      parameters:
      - description: body
        in: body
        name: bd
        required: true
        schema:
          $ref: '#/definitions/model.Client'
      responses:
        "200":
          description: OK
      summary: create user pool
      tags:
      - user
  /api/quick/user-pool/{poolId}:
    delete:
      description: delete user pool
      parameters:
      - description: user pool id
        in: path
        name: poolId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: delete user pool
      tags:
      - user
    get:
      description: list user pool
      parameters:
      - description: user pool id
        in: path
        name: poolId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: user pool info
      tags:
      - user
    put:
      description: modify user pool
      parameters:
      - description: user pool id
        in: path
        name: poolId
        required: true
        type: string
      - description: body
        in: body
        name: bd
        required: true
        schema:
          $ref: '#/definitions/model.UserPool'
      responses:
        "200":
          description: OK
      summary: modify user pool
      tags:
      - user
  /api/quick/user-pool/{poolId}/users:
    get:
      description: list users
      responses:
        "200":
          description: OK
      summary: user info
      tags:
      - user
    post:
      description: create user
      parameters:
      - description: body
        in: body
        name: bd
        required: true
        schema:
          $ref: '#/definitions/model.Client'
      responses:
        "200":
          description: OK
      summary: create user
      tags:
      - user
  /api/quick/user-pool/{poolId}/users/{user}:
    delete:
      description: delete user
      parameters:
      - description: user pool id
        in: path
        name: poolId
        required: true
        type: string
      - description: user id
        in: path
        name: userId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: delete user
      tags:
      - user
  /api/quick/user-pool/{poolId}/users/{userId}:
    get:
      description: list user
      parameters:
      - description: user pool id
        in: path
        name: poolId
        required: true
        type: string
      - description: user id
        in: path
        name: userId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: user info
      tags:
      - user
    put:
      description: modify user
      parameters:
      - description: user pool id
        in: path
        name: poolId
        required: true
        type: string
      - description: user id
        in: path
        name: userId
        required: true
        type: string
      - description: body
        in: body
        name: bd
        required: true
        schema:
          $ref: '#/definitions/model.UserPool'
      responses:
        "200":
          description: OK
      summary: modify user
      tags:
      - user
  /v1/oauth2/token:
    post:
      description: oauth2 token
      parameters:
      - description: client_id
        in: query
        name: client_id
        required: true
        type: string
      - description: client_secret
        in: query
        name: client_secret
        type: string
      - description: code
        in: query
        name: code
        type: string
      - description: grant_type
        in: query
        name: grant_type
        required: true
        type: string
      - description: redirect_uri
        in: query
        name: redirect_uri
        type: string
      - description: state
        in: query
        name: state
        type: string
      - description: nonce
        in: query
        name: nonce
        type: string
      responses:
        "200":
          description: OK
      summary: oauth2 token
      tags:
      - oauth2
securityDefinitions:
  Login:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
