definitions:
  controller.OpenidConfigurationDto:
    properties:
      authorization_endpoint:
        type: string
      claims_supported:
        items:
          type: string
        type: array
      id_token_signing_alg_values_supported:
        items:
          type: string
        type: array
      issuer:
        type: string
      jwks_uri:
        type: string
      request_uri_parameter_supported:
        type: boolean
      response_types_supported:
        items:
          type: string
        type: array
      scopes_supported:
        items:
          type: string
        type: array
      subject_types_supported:
        items:
          type: string
        type: array
      token_endpoint:
        type: string
      token_endpoint_auth_methods_supported:
        items:
          type: string
        type: array
      userinfo_endpoint:
        type: string
    type: object
info:
  contact: {}
  license:
    name: MIT
    url: https://github.com/hello-jiangxiaoyu/QuickAuth/blob/main/LICENSE
  title: swagger 接口文档
  version: "1.0"
paths:
  /api/quick/.well-known/jwks.json:
    get:
      description: get jwks
      responses:
        "200":
          description: OK
      summary: get jwks
      tags:
      - oidc
  /api/quick/.well-known/openid-configuration:
    get:
      description: get open id configuration
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.OpenidConfigurationDto'
      summary: get OIDC
      tags:
      - oidc
  /api/quick/login:
    post:
      description: login using username and password
      parameters:
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      - description: next
        in: query
        name: next
        type: string
      responses:
        "200":
          description: OK
      summary: login a user
      tags:
      - login
  /api/quick/login/provider-info:
    get:
      description: get all login provider information list
      responses:
        "200":
          description: OK
      summary: provider info
      tags:
      - login
  /api/quick/login/provider/{provider}:
    get:
      description: login third provider callback
      parameters:
      - description: provider name
        in: path
        name: provider
        required: true
        type: string
      - description: code
        in: query
        name: code
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: provider callback
      tags:
      - login
  /api/quick/logout:
    get:
      description: logout current user
      responses:
        "200":
          description: OK
      summary: logout current user
      tags:
      - login
  /api/quick/oauth2/auth:
    get:
      description: oauth2 authorize
      parameters:
      - description: client_id
        in: query
        name: client_id
        required: true
        type: string
      - description: scope
        in: query
        name: scope
        required: true
        type: string
      - description: response_type
        in: query
        name: response_type
        required: true
        type: string
      - description: redirect_uri
        in: query
        name: redirect_uri
        required: true
        type: string
      - description: state
        in: query
        name: state
        type: string
      - description: nonce
        in: query
        name: nonce
        type: string
      responses:
        "200":
          description: OK
        "302":
          description: Found
      summary: oauth2 authorize
      tags:
      - oauth2
  /v1/oauth2/token:
    post:
      description: oauth2 token
      parameters:
      - description: client_id
        in: query
        name: client_id
        required: true
        type: string
      - description: client_secret
        in: query
        name: client_secret
        type: string
      - description: code
        in: query
        name: code
        type: string
      - description: grant_type
        in: query
        name: grant_type
        required: true
        type: string
      - description: redirect_uri
        in: query
        name: redirect_uri
        type: string
      - description: state
        in: query
        name: state
        type: string
      - description: nonce
        in: query
        name: nonce
        type: string
      responses:
        "200":
          description: OK
      summary: oauth2 token
      tags:
      - oauth2
securityDefinitions:
  Login:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
